[env]
term = "xterm-256color"

[window]
blur = false
# padding = { x = 1, y = 1 }
dynamic_padding = true
decorations = "full"
option_as_alt = "OnlyRight"

[font]
size = 16
normal = { family = "Hack Nerd Font Mono", style = "Regular" }
bold = { family = "Hack Nerd Font Mono", style = "Bold" }
italic = { family = "Hack Nerd Font Mono", style = "Italic" }
bold_italic = { family = "Hack Nerd Font Mono", style = "Bold Italic" }
builtin_box_drawing = false

[cursor]
style = { shape = "Block", blinking = "Off" }

[general]
import = [
  "~/.config/alacritty/colorschemes/base16-default-dark.toml"
]
