--output "%(channel)s/%(playlist_title!$=videos&playlist|{})S/%(title)S_[%(width)S].%(ext)s"
--output "subtitle:%(channel)S/%(playlist_title!$=videos&playlist|{})S/subtitles/%(title)S_%(id)d.%(ext)s"
--output "thumbnail:%(channel)S/%(playlist_title!$=videos&playlist|{})S/thumbnails/%(title)S_%(id)d.%(ext)s"

--output-na-placeholder ""
--no-overwrite

--match-filter "title!*=Isaac"
# --format 'bestvideo+bestaudio'
--format 'bv[height>=720]+ba'
--format-sort '+res,size,vcodec:vp9'

--sub-langs 'eng,fr,fr.orig,-live_chat'
--write-auto-subs
--write-subs
--write-thumbnail

--mark-watched
--cookies youtube-cookies
--yes-playlist
--playlist-items "1:10"

# --download-archive "archives.log"
