----------------------------------------------------------------------------
-- Neovim LSP module
----------------------------------------------------------------------------
-- #Configurations
-- <!-- lspconfig-all lspconfig-server-configurations -->
--
-- LSP configs provided by nvim-lspconfig are listed below. This documentation is
-- autogenerated from the Lua files. You can view this file in Nvim by running
-- `:help lspconfig-all`.

return {
	enabled = true,
	lazy = false,
  priority = 30,
	"neovim/nvim-lspconfig",
  dependencies = {
    "williamboman/mason.nvim",
    "coq"
  }
}
