----------------------------------------------------------------------------
-- Neovim LSP module
----------------------------------------------------------------------------
-- #Configurations
-- <!-- *lspconfig-all* *lspconfig-server-configurations* -->
-- 
-- LSP configs provided by nvim-lspconfig are listed below. This documentation is
-- autogenerated from the Lua files. You can view this file in Nvim by running
-- `:help lspconfig-all`.

return {
	enabled = true,
	lazy = false,
  priority = 30,
	"neovim/nvim-lspconfig",
  dependencies = {
    "williamboman/mason.nvim",
    "coq"
  },
  opts = {
    -- options for vim.diagnostic.config()
    diagnostics = {
      underline = true,
      update_in_insert = false,
      virtual_text = {
        spacing = 4,
        source = "if_many",
        prefix = "icons",
      },
      severity_sort = true,
    },
    -- Enable this to enable the builtin LSP inlay hints on Neovim >= 0.10.0
    -- Be aware that you also will need to properly configure your LSP server to
    -- provide the inlay hints.
    inlay_hints = {
      enabled = true,
    },
    -- add any global capabilities here
    capabilities = {},
    -- Automatically format on save
    autoformat = true,
    -- Enable this to show formatters used in a notification
    -- Useful for debugging formatter issues
    format_notify = true,
    -- options for vim.lsp.buf.format
    -- `bufnr` and `filter` is handled by the LazyVim formatter,
    -- but can be also overridden when specified
    format = {
      formatting_options = nil,
      timeout_ms = nil,
    },
    terraform = {
      cmd= { "terraform-ls", "serve" },
      path = _G.home .. "/.local/share/nvim/mason/bin/"
    },
  },
  config = function(_, opts)
    -- vim.lsp.set_log_level("debug")
    -- vim.diagnostic.config(opts.diagnostics)
    -- vim.lsp.buf.format(opts.format)

    -- local lspconfig = require('lspconfig')
    -- local capabilities = require('coq').lsp_ensure_capabilities
    -- lspconfig.lua_ls.setup(capabilities(opts))
    -- lspconfig.terraform_lsp.setup(capabilities(opts.terraform))
    -- lspconfig.ansiblels.setup(capabilities(opts))
    -- lspconfig.yamlls.setup(capabilities(opts))
  end
}
