# autofit-larger=70%x100%
# autofit-smaller=20%x30%
geometry=50%x50%+50%+50%
# keep-open=yes
volume-max=100
# vo=gpu-next
# gpu-context=aut'

# =========================================
# === On-Screen Display (OSD) Settings ===
# =========================================
# Font name for the OSD (e.g., status messages, progress bar)
osd-font='Helvetica Neue'
# Font size for the OSD
osd-font-size=32
# Main OSD text color (ARGB/RGB hex)
osd-color='#FFFFFF'
# OSD border/outline color (ARGB/RGB hex)
osd-border-color='#000000'

[live]
cache=no
demuxer-hysteresis-secs = .5
demuxer-readahead-secs = 1
vp=gpu
hwdec=videotoolbox-copy
